version: "3.8"

networks:
  camaya-webservices:

services:

  camaya-services:
    container_name: camaya-services
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./:/var/www/html:delegated
    networks:
      - camaya-webservices

  web-server:
    container_name: webserver-nginx
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "8090:80"
    volumes:
      - ./backend/laravel-app:/var/www/html:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend-dev
      - mysql_db
    networks:
      - camaya-webservices


  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: camaya-services
      MYSQL_BOOKING_DATABASE: camaya-booking
    ports:
      - 3007:3007
    networks:
      - camaya-webservices


  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9002:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - camaya-webservices
