export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_CHECK = 'AUTH_CHECK';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const UPDATE_BOOKING_TABS = 'UPDATE_BOOKING_TABS';
export const UPDATE_BOOKING_PANE_ACTIVE_KEY = 'UPDATE_BOOKING_PANE_ACTIVE_KEY';

export const UPDATE_TRIPPING_TABS = 'UPDATE_TRIPPING_TABS';
export const UPDATE_TRIPPING_PANE_ACTIVE_KEY = 'UPDATE_TRIPPING_PANE_ACTIVE_KEY';

// USER